
services:
  db:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - /d/nestjs/test-nest-pro/postgres_data:/var/lib/postgresql/data
